### ISSUE TITLE
NT4 Setup Fails on PowerPC G4 upgraded B&W G3

### ISSUE THREAD

**Issue by WGriffithsBLI** [Wack0/maciNTosh#14]
Hey, so yes, me again, sorry! So my B&W G3 is actually upgraded to a G4 with a Sonnet card - yes, I was kinda curious if a wickedly fast NT4 PPC system was doable. Unfortunately the NT4 text-based setup screen halts at the below. 

![image](https://github.com/user-attachments/assets/8f18547c-8932-478b-9c5f-2af12314ef56)

Am wondering if anyone has had success with using this with a G4 CPU at all (as I know the Yikes G4 has to have ADB added for this to work), or whether this is the first attempt. I may be guessing here that maybe the setup is freaking out and failing to identify the CPU and thus returning the error.

**Comment by Wack0** [comment]
NT4's osloader and setupldr has an overzealous PVR check, if it's not in a hardcoded list it will fail like this.

The ARC firmware has code to patch this check out on load (for a PVR high 16 bits not in the list, patch all occurences of mfpvr to fake a PPC750 so the NT bootloader continues), evidentally that code is nonworking right now. I will investigate as soon as possible.

**Comment by Wack0** [comment]
Fixed in 07c734381b5d73cce94232e7a230bda72597166d and latest release v0.04.

**Comment by WGriffithsBLI** [comment]
Can confirm that the error is no longer impacting my machine! Thanks for this!
