### ISSUE TITLE
IDE Disks Not Detected on G3 B&W

### ISSUE THREAD

**Issue by Compgeke** [Wack0/maciNTosh#2]
Exactly what it's saying on the tin. When attempting to run the ARC setup on a B&W G3 the hard drive detection is not working. You'll get the option to "Select" however you only see "hd-1: (0MB)" and moving up to it hard locks the system.

This has ben tested with two real IDE hard drives (IDE and Quantum) as well as a Sandisk, a Cactus, an Exceed and an Innodisk Compact Flash card. 

Machine is a B&W G3/400 w/ Rage 128.

**Comment by Wack0** [comment]
It is mentioned in the readme that there are no drivers for PCI IDE controllers yet, for now ensure your hd is connected to the IDE controller on Paddington used for the optical drive and zip disk.

**Comment by Compgeke** [comment]
Hahaha turns out it was just a bad IDE cable. Nothing wrong here. Wow the routing sucks to replace it factory-like, definitely not gonna happen.
