### ISSUE TITLE
Will this work with NT4 Server?

### ISSUE THREAD

**Issue by JannGold** [Wack0/maciNTosh#20]
I was wondering if this supports Server versions of Windows NT 3.51 and NT4. I know this works with Workstation.

**Comment by Wack0** [comment]
NT 4 Server should work fine, but I think NT 3.51 Server setup *requires* a network driver to be installed

**Comment by JannGold** [comment]
Thank you! I found out about this and I realized that I had a G3 Blue and White that my dad got from his old job 10 years ago. I can try it when I can.

**Comment by nsapa** [comment]
Yes, I had Windows NT 4.0 Server running in DingusPPC with the initial release ([v0.01](https://github.com/Wack0/maciNTosh/releases/tag/v0.01)).
Just don't select PDC or BDC and don't configure any network.

**Comment by JannGold** [comment]
Yes it does. Works with NT 3.51 Server as well.
