### ISSUE TITLE
iBook Clamshell support when?

### ISSUE THREAD

**Issue by EGAMatsu** [Wack0/maciNTosh#22]
I'm just curious when the iBook Clamshell G3 will get support, I wanted to try this, burnt a disk, then realized it doesn't support the device yet.

**Comment by Buggem** [comment]
G3 and 4 have some differences, I'm not sure if this has anything to do with compatibility.

**Comment by Wack0** [comment]
Duplicate of #16 

Uni-North+KeyLargo support will happen eventually.

**Comment by EGAMatsu** [comment]
> G3 and 4 have some differences, I'm not sure if this has anything to do with compatibility.

I mean okay, what does that have to do with the iBook Clamshell, it's a G3, not a G4.
