### ISSUE TITLE
Glitches out on G3 Blue and White

### ISSUE THREAD

**Issue by JannGold** [Wack0/maciNTosh#24]
![image](https://github.com/user-attachments/assets/c560e4d5-2726-4021-a702-088736ce7d2e)

**Comment by Goldfish64** [comment]
What video card/display setup?

**Comment by JannGold** [comment]
My display is an Acer 1280 x 1024 AL1706. My GPU is a RAGE Pro. 
![image](https://github.com/user-attachments/assets/1bc82042-f9a8-43f0-973f-d5fe500d27ef)

**Comment by JannGold** [comment]
Most G3 machines I see have a RAGE 128.

**Comment by Wack0** [comment]
This is an ATI Rage DSP timing issue. I know my current dsp timing code for rage is incorrect and only works on lombard (and on imac G3 with slightly more flickering).

Unfortunately my lombard is currently out of action so i won't be able to test any such code for a while.

**Comment by Wack0** [comment]
Also: the screen wraparound at the bottom is interesting. I blindly put the card into 32bpp mode, but open firmware might have set it into a resolution where the card has not enough vram for 32bpp.

In that case, try changing the resolution in the open firmware shell, that might help a bit:
```
dev screen
show-modes
x set-mode
```
(where "x" is one of the mode numbers shown)
if it powers off the screen, you can still use the OF shell blind for `shut-down` or `reset-all`.

**Comment by JannGold** [comment]
I thought the screen wrap was very weird. I haven’t seen it before on that Mac or my monitor.

**Comment by JannGold** [comment]
Solved! My monitor was 5:4 ratio. I tried a Dell 4:3, and it worked!
