### ISSUE TITLE
early attempt to boot on PearPC emulator (cannot find boot file)

### ISSUE THREAD

**Issue by Barnacl437** [Wack0/maciNTosh#25]
When I discovered this, I think I may try on using PearPC instead of DingusPPC because I am more familiar to the pear one. 
It was able to detect the Arc FW partition...

![image](https://github.com/user-attachments/assets/473d877d-e550-497c-9519-04677ab5bea5)

But seems like it cannot find a boot file (portion of the PearPC log below).
Maybe the emulator fault or something. I haven't get much insight of this problem yet.

```
getStartBlock: 0 Apple_Free
getStartBlock: 1 Apple_Free
getStartBlock: 2 Apple_Free
getStartBlock: 3 Apple_Free
start: 512
cannot find boot file.
```
P/S: also during installation if any disc swap is required, then PearPC would not pass that, so rather an emulator thing.

**Comment by Wack0** [comment]
PearPC doesn't implement MSR_LE, nor does it emulate a supported system. dingusppc-nt is currently the only supported emulator.
