### ISSUE TITLE
(emulation) c1.exe doesn't work

### ISSUE THREAD

**Issue by Olekoop** [Wack0/maciNTosh#28]
When I am trying to run cl (version 10.10.6101) on your dingusppc fork, it complains about c1.exe failing to initialize properly (0xc000001d).

c1.exe is very flaky, sometimes it shows the message, sometimes it doesn't. Very rarely (probably when lauching it first time) it actually works.

When I tried to use Windbg to debug, I noticed that the crash happens on location 0x1030108c and the register Gpr0 has the same value. When c1.exe starts, the Gpr0 is set to a specific address in code. When executing manually line by line in Windbg, the Gpr0 doesn't change, but as soon as you let c1.exe go, the Gpr0 register is set to 0x1030108c. Pehaps it is a emulation bug?

**Comment by Wack0** [comment]
emulation bugs for a different project don't belong here. and i really don't care about emulation bugs in dingusppc-nt actually, it's my hacked together fork to get NT to boot (and nothing else) so I can debug issues in *kernelmode* easier.
