### ISSUE TITLE
Graphical Corruption with Rage 128 on B&W G3

### ISSUE THREAD

**Issue by Compgeke** [Wack0/maciNTosh#3]
Another fun not-Powerbook bug. The factory Rage 128 does not seem to be functioning as intended with the ATI driver support. The display has vertical lines through and text is both massive and wrapping. Image is attached.

![G3_NT4_GraphicalCorruption](https://github.com/user-attachments/assets/bcf80acc-6447-4185-9bdf-ff1d1c3b9e29)
![G3_NT4_GraphicalCorruption2](https://github.com/user-attachments/assets/027630e2-bfa1-4c98-b516-37091abc1646)

**Comment by Wack0** [comment]
I'll reverse the OS9 driver for that card when I get time, to see if I'm missing anything in particular, but given that I don't have the hardware, there's only so much I'll be able to do.

What does open firmware fcode set up the card to be? I just blindly try to set 32bpp, so if some card comes up in 1024x768 and doesn't have enough vram to handle 32bpp in that resolution I'm sure there will be issues there.

**Comment by Wack0** [comment]
(some reversing later)

...turns out the various MMIO registers are in totally different positions on these cards! no wonder the modeswitch isn't working correctly lol

**Comment by Wack0** [comment]
Can you try the latest release? Hopefully it will at least try to modeswitch, but without having the hardware there's not much else I can suggest other than experimenting with the timing registers...

**Comment by Compgeke** [comment]
No such luck, actually seems to have made it a bit worse. I'll see if I can poke around a bit later once I get some free time. If there's anything you'd like me to poke at with the real hardware I can definitely try. 

![G3_NT4_GraphicalCorruption_0 2](https://github.com/user-attachments/assets/18db4921-dbdb-4a1c-9701-1264f5a12cc0)

**Comment by Wack0** [comment]
Can you try this? This adds a write to the hsync start/width register, which I only didn't implement because I observed no difference on lombard, but probably is important on desktops lol.

[nt_arcfw_grackle_fwonly_test20240713_1731.zip](https://github.com/user-attachments/files/16202938/nt_arcfw_grackle_fwonly_test20240713_1731.zip)

**Comment by Compgeke** [comment]
Unfortunately no luck with that either, exact same thing.

**Comment by Wack0** [comment]
Yeah, I just found out that the MMIO base address for the rage4 cards are at a different assigned-address.

Try this one.
[nt_arcfw_grackle_fwonly_test20240713_1955.zip](https://github.com/user-attachments/files/16203392/nt_arcfw_grackle_fwonly_test20240713_1955.zip)

**Comment by Compgeke** [comment]
Good news, that one's actually improved it a bit! It's not 100% perfect but it's no longer wrapped, just blue and triplicated. 

![G3_NT4_GraphicalCorruption3](https://github.com/user-attachments/assets/170329dc-ae0b-48ea-81b2-6d39d5edbe52)

**Comment by Wack0** [comment]
yeah, that's probably DSP timing issues...

can you try this one?

[nt_arcfw_grackle_fwonly_test20240713_2005.zip](https://github.com/user-attachments/files/16203406/nt_arcfw_grackle_fwonly_test20240713_2005.zip)

**Comment by Compgeke** [comment]
Got the same result with it.

**Comment by Wack0** [comment]
ok, so the hsync register doesn't matter it seems?

can you try this?

[nt_arcfw_grackle_fwonly_test20240713_2013.zip](https://github.com/user-attachments/files/16203418/nt_arcfw_grackle_fwonly_test20240713_2013.zip)

**Comment by Compgeke** [comment]
With this version, we've got the same triplicating/blue lines but now the display's actually all black. No more readable text or anything.
![G3_NT4_GraphicalCorruption4](https://github.com/user-attachments/assets/d07e5964-a42a-4cc7-94f6-bd2cbb3018d6)

**Comment by Wack0** [comment]
ok, can you try this one? just want to see what it does when the DSP timing registers aren't touched:

[nt_arcfw_grackle_fwonly_test20240713_2024.zip](https://github.com/user-attachments/files/16203446/nt_arcfw_grackle_fwonly_test20240713_2024.zip)

**Comment by Compgeke** [comment]
With that one back to the normal blue/triplicate stuff.

**Comment by Wack0** [comment]
looking at the register documentation again, one of the DSP registers are slightly different on rage4, two of the fields changed positions.

try this one:

[nt_arcfw_grackle_fwonly_test20240713_2037.zip](https://github.com/user-attachments/files/16203472/nt_arcfw_grackle_fwonly_test20240713_2037.zip)

**Comment by Compgeke** [comment]
This one's actually getting a bit closer. The entire display is now blue, although there's still broken text and some duplication.

![G3_NT4_GraphicalCorruption5](https://github.com/user-attachments/assets/336e4112-26b8-4ee4-911c-c2ca2e5791d6)

**Comment by Wack0** [comment]
ok, so it is DSP timing stuff...

just saw an issue with the DAC gamma table, so hopefully this at least fixes the colours:

[nt_arcfw_grackle_fwonly_test20240713_2045.zip](https://github.com/user-attachments/files/16203483/nt_arcfw_grackle_fwonly_test20240713_2045.zip)

**Comment by Compgeke** [comment]
That is correct! Now have proper color. 
![G3_NT4_GraphicalCorruption6](https://github.com/user-attachments/assets/4a3f67e2-adb4-4aae-a9be-b6f87a522024)

**Comment by Wack0** [comment]
ok, can you try this one?

[nt_arcfw_grackle_fwonly_test20240713_2225.zip](https://github.com/user-attachments/files/16203681/nt_arcfw_grackle_fwonly_test20240713_2225.zip)

**Comment by Compgeke** [comment]
Getting closer. Now the colors are correct and the text is readable. 
![G3_NT4_GraphicalCorruption7](https://github.com/user-attachments/assets/fa1f23c2-1c1e-403e-8c88-f6335491011b)

**Comment by Wack0** [comment]
this is now just trial and error of dsp timing register changes and observing the output:

[nt_arcfw_grackle_fwonly_test20240713_2239.zip](https://github.com/user-attachments/files/16203695/nt_arcfw_grackle_fwonly_test20240713_2239.zip)

**Comment by Compgeke** [comment]
This one lost the color lines, but we're back to the same missing text as the 2nd previous test.

**Comment by Wack0** [comment]
[nt_arcfw_grackle_fwonly_test20240713_2248.zip](https://github.com/user-attachments/files/16203714/nt_arcfw_grackle_fwonly_test20240713_2248.zip)

**Comment by Compgeke** [comment]
![G3_NT4_GraphicalCorruption8](https://github.com/user-attachments/assets/264fbb8d-4235-4425-ae7e-460ecd608135)

**Comment by Wack0** [comment]
tried reimplementing how the linux driver sets the DSP timings, along with reimplementing how the OS9 driver gets the vclk

[nt_arcfw_grackle_fwonly_test20240713_2331.zip](https://github.com/user-attachments/files/16203813/nt_arcfw_grackle_fwonly_test20240713_2331.zip)

**Comment by Compgeke** [comment]
Good news! That one's fixed it. We now have properly functioning Rage 128 graphics. 
![G3_NT4_GraphicalCorruption89](https://github.com/user-attachments/assets/67e610da-076e-43bb-af90-640d1909c60f)

**Comment by JonObst** [comment]
With this latest test zip, NT bootloader freezes here:

![image](https://github.com/user-attachments/assets/5d930903-7eae-420d-9372-bfdfb9fc8ee4)

Not sure if this was supposed to be a fully working ISO or if it has bits missing, apologies if it is the latter.

**Comment by Compgeke** [comment]
Just curious, did you get through the text-mode setup and all that jazz yet? I'm not able to actually make it through the setup at all, documented here: https://github.com/Wack0/maciNTosh/issues/5

**Comment by JonObst** [comment]
No, I only got as far as loading the drivers - I hadn't yet been asked to select a keyboard layout.

**Comment by Wack0** [comment]
OK, this crash on boot looks like HAL dying early. Possibly PCI related, which I tried to work around as I read somewhere that blindly enumerating the PCI bus on these systens can freeze, but I probably didn't do it right due to lack of real hardware to test with. Different issue anyway.

(And yes, the driver name is different, due to being my own test ISO rather than a properly cleaned up release build.)

Regarding this specific issue, I'll clean things up for commit and release later.

**Comment by Wack0** [comment]
This is fixed by https://github.com/Wack0/maciNTosh/commit/cc6fe4964fdfbd87b03dba1a1468ed966641e511 although I'd rather wait to fix #8 before making another release. In any case, closing this issue now.
