### ISSUE TITLE
Emulator compatibility?

### ISSUE THREAD

**Issue by BurnedPinguin** [Wack0/maciNTosh#30]
Apart from QEMU, which I know was used during the development process, which other emulators could work? I tried SheepShave and PearPC, both of these just do not acknowledge the disc as bootable, even when I use a B&W G3 ROM with them (machines that they officially support). I also tried DingusPPC but that one only does the old world machines, and when I give it a new world rom it also doesn't recognise the disc as bootable.

**Comment by Wack0** [comment]
qemu does not work for the gossamer port. Use dingusppc-nt which is my dingus tree I used for dev/testing: https://github.com/Wack0/dingusppc-nt

neozeed made a video about installing under emulation: https://www.youtube.com/watch?v=c6L_AhiiBGQ
