### ISSUE TITLE
Does not detect the connected IDE disk on B&W

### ISSUE THREAD

**Issue by VitaliyYakob** [Wack0/maciNTosh#34]
I can't understand what's going on. 

I Have Power Macintosh G3 B&W Rev. B, the boot environment does not detect the connected IDE disk. I tried IDE drives, as well as an SSD connected via a SATA-IDE bridge.
In OS9, the disk is displayed and works fine, but here it simply does not display it.
Is there any option for diagnosis? Can a DVD drive from another Mac model prevent the HDD from being detected?

I also noticed that
The adaptec Ava-2906 SCSI card may cause boot problems, for example, the ADB keyboard may not work.
The Cisco Air-PCI350 Wi-Fi card prevents the graphics from booting -- just a black screen.
If there are no disks, select, for example, "Repartition disk for NT installation" and press the up arrow, "Select a disk" is replaced with "Selehd-1: (0MB) - "
<img width="614" alt="select" src="https://github.com/user-attachments/assets/f7a8b55f-9880-4a58-8396-a23d1424b976">
<img width="598" alt="selehd" src="https://github.com/user-attachments/assets/1aae0656-f499-43a1-bcce-a38f3efe0ddb">

**Comment by Wack0** [comment]
the PCI IDE controller used normally for the HD is not supported yet, you need to use the other controller (the one used for optical drive and zip disk)

**Comment by VitaliyYakob** [comment]
Oh, that's right. I was not attentive when reading the description.
