### ISSUE TITLE
Demonstration?

### ISSUE THREAD

**Issue by compaqpresario** [Wack0/maciNTosh#4]
I was wondering if either this port's author or someone who has gotten it working to make a short video demonstrating NT on actual New World Mac hardware. It seems like there are some problems with ATI graphics card compatibility so I'd like an idea of what a successful install looks like before I try it out.

**Comment by binarymaster** [comment]
See video attached to this post: https://twitter.com/dosdude1/status/1811913735767720031

**Comment by compaqpresario** [comment]
Thanks
