### ISSUE TITLE
Instructions on creating the bootable image?

### ISSUE THREAD

**Issue by Absolucy** [Wack0/maciNTosh#46]
It'd be nice to have some sort of instructions on creating a bootable image somewhere. The current readme isn't very specific at all, mainly this part:
> For recreating the image from a folder dump, use your preferred tool to create a hybrid HFS+ISO image, make sure `System` folder is blessed and `BootX` file is of type `tbxi`.

**Comment by Wack0** [comment]
neozeed's blog post has the exact method I use: https://virtuallyfun.com/2024/07/13/rairiis-incredible-port-of-arc-drivers-for-nt-powerpc-to-g3-macintoshes/

**Comment by Absolucy** [comment]
that was helpful and worked, thanks!
