### ISSUE TITLE
HD fails to boot ARC on G3 Clamshell

### ISSUE THREAD

**Issue by queenkjuul** [Wack0/maciNTosh#47]
I'm scared because now I can't get into OpenFirmware :eek:

mac bongs on power up but screen stays black no matter what

Everything was working *perfectly* with one exception: I could only boot ARC from USB, the installed version on the HD would not load. 

I went into OF and verified that the bootlader was there with `dir hd:,\` which showed `stage1.elf` and `stage2.elf`

I tried `boot hd:,\stage1.elf` and the screen just went black. This was same as choosing the Windows HD option in multi-boot

I tried `boot hd:,\stage2.elf` and it said somethign about "resetting" something but refused to boot. I tried `boot hd:,\stage1.elf` again, and got the same error (no black screen, just the error)

~~I ran~~ ~~`shut-down`~~ ~~and now I'm here where it powers on, beeps, disks spin up, but no screen.~~

~~Please don't tell me I bricked my baby :sob: but it was my own stupidity...~~

**Comment by queenkjuul** [comment]
Ah ok, not bricked lol, had never gotten an old Mac into that state but holding power+command for a long time reset it

Still can't boot from HD though.

**Comment by Wack0** [comment]
does the hd show up in the multi-boot menu?

which version of osx are you booting from?

**Comment by queenkjuul** [comment]
The HD does show up in multi boot, but selecting it just leads to a black screen. I have been mostly trying 10.2.0 retail CD, i was going to try 10.3.0 next then 10.4.8

**Comment by Wack0** [comment]
I know someone else with a G3 Clamshell had a similar issue, turned out the HD was dying, the area of disk where the ARC firmware writes the boot partition to is usually used to store an OS9 driver that isn't really used by the system...

**Comment by queenkjuul** [comment]
hm, I cannot rule that out, this is the original 25-year-old 3GB HDD. However, it otherwise seems to be working perfectly. 

I have finally gotten OS X 10.1.5 to boot from CD, into Disk Utility, and find all the relevant partitions. That has let me format the Mac partitions, and now I've installed OS 9 drivers, so I'll see if I can get Mac OS booting. 

I think I could live with having to boot from USB to use Windows, but it would be preferred not to of course. Maybe I will order a replacement drive, but I've had no issues with Mac OS at all so far

**Comment by queenkjuul** [comment]
So I've gone ahead and made the same attempt on my white iBook G3 600MHz and I have the exact same problem - after installing ARC firmware to HDD, booting from HDD results in just a black screen. Booting from USB continues to work fine.

**Comment by queenkjuul** [comment]
oh wow the new Gossamer update - native multibooting like that, amazing! B&W G3 still on the wishlist though :disappointed: 

anyway thanks for the awesome work, wonder what's weird with my iBooks... but I am bad luck with computers lol they break in new and exciting ways for me

**Comment by queenkjuul** [comment]
ah so I am an idiot, and had flashed v0.2 to my USB. v0.3 works perfectly on the 600MHz. The clamshell I have not tried again, but I am having issues installing Rhapsody 5.6, which should work on that machine, so I'm an inching closer to the "bad HDD" theory, though OS 9 and OS X seem perfectly happy otherwise
