### ISSUE TITLE
"Setup did not find a keyboard connected to your computer." on PowerBook5,2

### ISSUE THREAD

**Issue by lkcomputes** [Wack0/maciNTosh#48]
I was trying to install NT Workstation 4.0 SP1 via the Mac99 0.03 release on my 2003 Aluminum PowerBook G4 (PowerBook5,2) when I got this error following the beginning of setup.
![image](https://github.com/user-attachments/assets/efffaa1e-dc62-44b3-bc55-1f4916fb618f)
I haven't found any prior issues that mention something like this. The same result occurs with NT Server 4.0 RTM.

**Comment by Wack0** [comment]
Did you load the PowerMac General HID & Storage driver?

**Comment by lkcomputes** [comment]
Nope, I'm a dumbass!
![image](https://github.com/user-attachments/assets/e249b287-9a07-44b2-9e94-e14578d2c61f)
This is why you thoroughly read instructions.
