### ISSUE TITLE
iBook G4

### ISSUE THREAD

**Issue by Demine0** [Wack0/maciNTosh#7]
after booting binary elf files from openfirmware, my ibook g4 won't start, only cd spinning, no image but chime, also the numpad LED lights up when f5 is pressed, not f6 as it was from the factory. A1133, powerbook6,7

**Comment by Wack0** [comment]
if you loaded stage2.elf manually, you just bricked your system (open firmware "helpfully" enables the broken little endian mode when loading a little endian elf, thanks apple) which is currently unsupported anyway (newer uni-north chipset). There is a recovery mode, but nobody figured out how to get to that bootrom code path yet on uninorth systems. Probably some test point on the motherboard.

The only known way to recover on uni-north systems would be to rewrite the NVRAM areas of flash manually by dumping the flash and rewriting using hardware.

I have had a few ideas (for example, the trick with removing ram that's used to reset open firmware password might work) but I am of course unwilling to brick my only uninorth system to find out.

People can't read readmes or error messages, it seems.

**Comment by Demine0** [comment]
please warn about this with big red font in readme

**Comment by Wack0** [comment]
I already mentioned the list of compatible systems in readme.

I planned to have measures against this, but only when uni-north systems are compatible (the currently compatible systems can be revived easily by pmu/cuda reset).

**Comment by WamWooWam** [comment]
As a small olive branch, you can try some of the steps here https://forums.macrumors.com/threads/so-you-think-you-bricked-it.2161970/

**Comment by Demine0** [comment]
> As a small olive branch, you can try some of the steps here https://forums.macrumors.com/threads/so-you-think-you-bricked-it.2161970/

Thanks, i tried this but no results. I think this ibook g4 have only one way with flashing flash chip

**Comment by Demine0** [comment]
using this instruction, ibook g4 get unbricked, https://mac-classic.com/articles/resetting-a-bricked-mac-that-wont-boot/

**Comment by Wack0** [comment]
thanks! that's what I was missing, I thought it was something deep on the logic board, but nope, just holding power+command is the keycombo to make the bootrom go into the other mode!
