### ISSUE TITLE
HAL crashes during initialisation on Cuda systems

### ISSUE THREAD

**Issue by Wack0** [Wack0/maciNTosh#8]
As reported by @JonObst here: https://github.com/Wack0/maciNTosh/issues/3#issuecomment-2227171714

Most likely an issue with PCI bus enumeration in the HAL.

**Comment by Wack0** [comment]
Here is a test build that may fix the issue. If not, I'll make a build with all the PCI bus enumeration testing code in...
[nt_arcfw_grackle_fwonly_test20240714_1248.zip](https://github.com/user-attachments/files/16216667/nt_arcfw_grackle_fwonly_test20240714_1248.zip)

**Comment by JonObst** [comment]
Same problem with the most recent build (1536)

**Comment by Wack0** [comment]
Hmm, not even displaying an additional message for detecting Yosemite?

I'll make another build with more debug logs as soon as possible.

**Comment by JonObst** [comment]
Right, just one dot then the freeze, nothing else displayed.

**Comment by Wack0** [comment]
OK, here's a build with the PCI debug output present in the HAL:

[nt_arcfw_grackle_fwonly_test20240714_1917.zip](https://github.com/user-attachments/files/16228394/nt_arcfw_grackle_fwonly_test20240714_1917.zip)

**Comment by JonObst** [comment]
![IMG_0147](https://github.com/user-attachments/assets/74f9f45e-a843-4a42-aae6-837b2d8b1cf0)

This is still all I get.  Just to confirm, I repartitioned the drive, ran setupldr, added the mass storage devices (2), selected the Mac type and video type, then it hangs here.

**Comment by Wack0** [comment]
Looking further, I think the Cuda driver in the HAL may be incorrect. (well, does things different that what I thought)

I made some changes, does this work?

[nt_arcfw_grackle_fwonly_test20240714_1952.zip](https://github.com/user-attachments/files/16228479/nt_arcfw_grackle_fwonly_test20240714_1952.zip)

**Comment by JonObst** [comment]
Unfortunately it does the exact same as before.

**Comment by Wack0** [comment]
Made another change, and also added a bunch of debug output to the cuda init:

[nt_arcfw_grackle_fwonly_test20240714_2106.zip](https://github.com/user-attachments/files/16228641/nt_arcfw_grackle_fwonly_test20240714_2106.zip)

**Comment by JonObst** [comment]
![IMG_0154](https://github.com/user-attachments/assets/1858bfee-a00f-4eda-8260-2082e79635d8)

well it’s showing the stop error now, progress!

**Comment by JonObst** [comment]
also I believe it made it further than it had been before the halt

**Comment by Wack0** [comment]
yeah, now it is a pci enumeration issue.

**Comment by Wack0** [comment]
this one has more PCI debug output, should hopefully say what's causing the machine check exception:

(also removed the cuda debug output because it's no longer needed)

[nt_arcfw_grackle_fwonly_test20240714_2204.zip](https://github.com/user-attachments/files/16228786/nt_arcfw_grackle_fwonly_test20240714_2204.zip)

**Comment by Wack0** [comment]
Just noticed something in the linux sources, where on Yosemite it turns off master abort mode in the PCI-PCI bridge, so I added code to do the same thing in the HAL when finding a PCI-PCI bridge - maybe that'll help.

[nt_arcfw_grackle_fwonly_test20240714_2237.zip](https://github.com/user-attachments/files/16228852/nt_arcfw_grackle_fwonly_test20240714_2237.zip)

**Comment by ActionRetro** [comment]
Also trying on a B&W G3 -  version nt_arcfw_grackle_fwonly_test20240714_2237.zip has the same result.
![IMG_8838](https://github.com/user-attachments/assets/9c299703-34db-437c-bd9c-01c778e6636c)

**Comment by JonObst** [comment]
Yep I get the same as Sean
![IMG_0156](https://github.com/user-attachments/assets/c4edadb6-8cf0-4573-b457-b9ec060f5e82)

**Comment by Wack0** [comment]
huh, maybe a timing issue on the cuda init?

**Comment by JonObst** [comment]
I’d say your guess is as good as mine, but your guess is actually 100x better than mine.

**Comment by joevt** [comment]
When porting pciutils to Mac OS X for PowerPC Macs, I found that probing non-existent devices behind the built-in PCI-PCI bridge of a B&W G3 causes a check exception so now it has a special case where it only probes PCI devices that exist in the device-tree.
 https://github.com/joevt/directhw/blob/a1d987fdea92ddf19cc877c4acef9b1ca2e06072/DirectHW/DirectHW.cpp#L1222-L1278

**Comment by Wack0** [comment]
@joevt According to the 21154 datasheet, turning off master abort mode like linux does causes exactly the behaviour you describe:

"Controls the 21154’s behavior when a master abort termination occurs in response to a transaction initiated by the 21154 on either the primary or secondary PCI interface.
When 0: The 21154 asserts TRDY# on the initiator bus for delayed transactions, and FFFF FFFFh for read transactions. For posted write transactions, p_serr_l is not asserted.
When 1: The 21154 returns a target abort on the initiator bus for delayed transactions. For posted write transactions, the 21154 asserts p_serr_l if the SERR# enable bit is set in the command register.
Reset value: 0."

It appears that `probe-slots` in yosemite's OF does enable this bit.

**Comment by joevt** [comment]
> It appears that `probe-slots` in yosemite's OF does enable this bit.

Yes. It's a standard PCI-PCI bridge register but this only happens for the built-in DEC21154 PCI bridge - not any other bridges (including other DEC21154 bridges that you may add).

The bridge control register is set to 0x0326 (hard coded) after the slots are probed.
1: SERR# Enable
2: ISA Enable
5: Master-Abort Mode
8: Primary Discard Timer
9: Secondary Discard Timer

The bridge control register is set to 0x03a6 before Open Firmware.
7: Fast Back-to-Back Enable
... + all the other bits mentioned above.

Any other PCI bridges that are not the built-in DEC21154 PCI bridge get their bridge control registers set to 0 before probing and 4 (ISA Enable) after probing.

**Comment by Wack0** [comment]
ok, is it definitely freezing there? boot should continue after that, either with INACCESSIBLE_BOOT_DEVICE or getting into text setup.

can you try not loading the general HID and storage driver? if it boots to a keyboard error, this would imply more issues in the Cuda driver...

**Comment by JonObst** [comment]
Fairly certain, the optical drive turned off as it has done in the past when the system freezes and I let it sit there for a couple of minutes with no progress - but I will recheck again after I return home from work this afternoon.

**Comment by ActionRetro** [comment]
Same result here.
![IMG_8851](https://github.com/user-attachments/assets/3e5a6784-8cb4-4b16-95b0-42810c830fa4)

**Comment by Wack0** [comment]
@ActionRetro is that with not loading the general HID and storage driver?

**Comment by ActionRetro** [comment]
Oh no, I'll try that

**Comment by Wack0** [comment]
if that boots to a keyboard error, then I know it's a HAL Cuda driver problem, otherwise something else (and probably related to the PCI IDE controller in some way, atapi.sys does load so it will try to use it)

**Comment by ActionRetro** [comment]
Ok, without HID and storage driver,
![IMG_8852](https://github.com/user-attachments/assets/9182a2e2-7ccd-4d39-871a-a00e4181728f)
 I got:

**Comment by Wack0** [comment]
OK, I meant with the mac i/o ide driver and not the "generic HID and storage" driver; but that actually helps! it shows me that atapi.sys initialiased fine, so it definitely is a cuda driver problem.

In that case, I noticed the linux driver did readback IER after writing to it to disable all MCU interrupts, so I tried that (instead of a delay after setting it on init). Might not work, but I guess linux driver did specifically do that for a reason, so:

[nt_arcfw_grackle_fwonly_test20240715_1729.zip](https://github.com/user-attachments/files/16237563/nt_arcfw_grackle_fwonly_test20240715_1729.zip)

**Comment by Wack0** [comment]
Given the previous build did not work (on a trayloading imac), I added some debug output for Cuda, hopefully the crash isn't what I think it is...

[nt_arcfw_grackle_fwonly_test20240715_1834.zip](https://github.com/user-attachments/files/16238152/nt_arcfw_grackle_fwonly_test20240715_1834.zip)

**Comment by TechandMusic462** [comment]
Debug output on the Trayloader:

![PXL_20240715_174618944 MP](https://github.com/user-attachments/assets/6eb1ce62-054b-4a6e-a72a-62a25ff83575)

**Comment by Wack0** [comment]
...I think I figured out what the problem was, how did this ever work, even under emulation??? (forgot to check if cuda was finished sending data, something I implemented in the ARC firmware even!)

I removed all the debug output, I can add it back if this still freezes.

[nt_arcfw_grackle_fwonly_test20240715_1913.zip](https://github.com/user-attachments/files/16238503/nt_arcfw_grackle_fwonly_test20240715_1913.zip)

**Comment by Wack0** [comment]
I assume the keyboard works fine in text setup?

**Comment by TechandMusic462** [comment]
Yes, I am currently at the formatting stage of the install.

**Comment by Wack0** [comment]
In that case, this issue is fixed, I'll get a release together.
