### ISSUE TITLE
(suggestion) will there ever be support for imac g3? (slot loading)

### ISSUE THREAD

**Issue by yumikonoua** [Wack0/maciNTosh#9]
It would be really cute and interesting.. please let me know.

**Comment by Wack0** [comment]
uni-north port will happen eventually.

**Comment by yumikonoua** [comment]
thanks!

**Comment by takasky85** [comment]
I know this doesn't work yet but I was just trying it in QEMU for giggles.

![image](https://github.com/user-attachments/assets/6d6b13d5-ff08-4abc-bd86-e430936ccd30)

**Comment by Wack0** [comment]
Going to close this now as the uni-north port effort has its own issue #32
